import ReesDefects.Rees.DegreePieces

/-!
# ReesDefects.Rees.CanonicalGenerators

Degree-one generators for the Rees algebra.
-/

noncomputable section

namespace ReesDefects
namespace Rees

universe u

open Polynomial

variable {R : Type u} [CommRing R]

/-- The canonical degree-one Rees algebra generator attached to an element of the ideal `I`. -/
def degreeOneGenerator (I : Ideal R) : I → ReesElem I :=
  fun x => ⟨Polynomial.monomial 1 x.1, (monomial_mem_iff I).2 (by simp [x.2])⟩

@[simp]
theorem degreeOneGenerator_coe (I : Ideal R) (x : I) :
    ((degreeOneGenerator I x : ReesElem I) : R[X]) = Polynomial.monomial 1 x.1 :=
  rfl

@[simp]
theorem coeff_degreeOneGenerator_one (I : Ideal R) (x : I) :
    ((degreeOneGenerator I x : ReesElem I) : R[X]).coeff 1 = x := by
  simp [degreeOneGenerator]

@[simp]
theorem coeff_degreeOneGenerator_ne_one (I : Ideal R) {n : ℕ} (h : n ≠ 1) (x : I) :
    ((degreeOneGenerator I x : ReesElem I) : R[X]).coeff n = 0 := by
  simp [degreeOneGenerator, coeff_monomial, h.symm]

/-- The polynomial range of the packaged degree-one generators is exactly Mathlib's mapped ideal. -/
theorem range_degreeOneGenerator_eq_map_monomial (I : Ideal R) :
    Set.range (fun x : I => ((degreeOneGenerator I x : ReesElem I) : R[X])) =
      (Submodule.map (Polynomial.monomial 1 : R →ₗ[R] R[X]) I : Set R[X]) := by
  ext p
  constructor
  · rintro ⟨x, rfl⟩
    exact Submodule.mem_map.mpr ⟨x, x.2, rfl⟩
  · intro hp
    rcases Submodule.mem_map.mp hp with ⟨x, hx, rfl⟩
    exact ⟨⟨x, hx⟩, rfl⟩

/-- The Rees algebra is generated by the packaged degree-one generators. -/
theorem adjoin_degreeOneGenerator_eq_reesAlgebra (I : Ideal R) :
    Algebra.adjoin R (Set.range fun x : I => ((degreeOneGenerator I x : ReesElem I) : R[X])) =
      reesAlgebra I := by
  rw [range_degreeOneGenerator_eq_map_monomial]
  exact adjoin_degree_one_eq I

end Rees
end ReesDefects
